/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package laurent.fitness;

import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;



@SpringBootApplication
public class Fitness implements CommandLineRunner {
	
//	@Autowired
//	private EntityManager entityManager;
//	
//	@Autowired
//	private AuthorityService authorityService;
//	
//	@Autowired
//	private UserService userService;
//	
//	@Autowired
//	private StaffService staffService;
//	
   public boolean someLibraryMethod() {
        return true;
    }



	public static void main(String[] args) throws Exception, MalformedURLException, IOException, ClassNotFoundException, SQLException {
		SpringApplication.run(Fitness.class, args);
	}

	@Override
	public void run(String... args)
			throws Exception,  MalformedURLException, IOException, ClassNotFoundException, SQLException {
		
//		BCryptPasswordEncoder bcrypt = new BCryptPasswordEncoder();
//		
//		this.authorityService.saveAuthority(new Authority("db_sam", "ROLE_ADMIN"));
//		int idUser = this.userService.findByUsernameIdMax();
//	
//		
//		this.staffService.saveStaff(new Staff(idUser,"db_sam", "db_sam", "{bcrypt}" + bcrypt.encode("simplon"), "", "", new Date(), (byte)(1)));
		
//		
//		
//			
//		StoredProcedureQuery storedProcedure = entityManager.createStoredProcedureQuery("proc_insert_data");
//	    storedProcedure.execute();
//	    
//	    //storedProcedureEnd permet de savoir quand est-ce que l'import est fini
//	    StoredProcedureQuery storedProcedureEnd = entityManager.createStoredProcedureQuery("proc_insert_end");
//	    storedProcedureEnd.execute();
				

	}
	
	
    
}
