/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fitness;

import org.junit.Test;

import laurent.fitness.Fitness;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Fitness classUnderTest = new Fitness();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
