-- MySQL Script generated by MySQL Workbench
-- mar. 26 mars 2019 15:34:48 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_fitness
-- -----------------------------------------------------
-- Base de données servant de support au projet chef-d'oeuvre
DROP SCHEMA IF EXISTS `db_fitness` ;

-- -----------------------------------------------------
-- Schema db_fitness
--
-- Base de données servant de support au projet chef-d'oeuvre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fitness` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_fitness` ;

-- -----------------------------------------------------
-- Table `db_fitness`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Customer` (
  `Users_username` VARCHAR(45) NOT NULL,
  `domesticAddress` VARCHAR(255) NOT NULL,
  `domesticCp` VARCHAR(15) NOT NULL,
  `domesticCity` VARCHAR(45) NOT NULL,
  `domesticCountry` VARCHAR(45) NOT NULL,
  `deliveryAddress` VARCHAR(255) NOT NULL,
  `deliveryCp` VARCHAR(45) NOT NULL,
  `deliveryCity` VARCHAR(45) NOT NULL,
  `deliveryCountry` VARCHAR(45) NOT NULL,
  `dateOfBirthday` DATE NULL,
  PRIMARY KEY (`Users_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Staff` (
  `Users_username` VARCHAR(45) NOT NULL,
  `dayWorking` VARCHAR(45) NOT NULL,
  `hourWorking` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Users_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Users` (
  `username` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(15) NULL,
  `dateOfRegistration` DATE NOT NULL,
  `Customer_Users_username` VARCHAR(45) NULL,
  `Staff_Users_username` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_Users_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Staff1`
    FOREIGN KEY (`Staff_Users_username`)
    REFERENCES `db_fitness`.`Staff` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `db_fitness`.`Users` (`email` ASC);

CREATE UNIQUE INDEX `idUser_UNIQUE` ON `db_fitness`.`Users` (`idUser` ASC);

CREATE INDEX `fk_Users_Customer1_idx` ON `db_fitness`.`Users` (`Customer_Users_username` ASC);

CREATE INDEX `fk_Users_Staff1_idx` ON `db_fitness`.`Users` (`Staff_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Authorities` (
  `Users_username` VARCHAR(45) NOT NULL,
  `authority` VARCHAR(45) NOT NULL DEFAULT 'ROLE_ANONYMOUS',
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Users_username`),
  CONSTRAINT `fk_Authorities_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`SubscriptionCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SubscriptionCategory` (
  `idSubscriptionCategory` INT NOT NULL AUTO_INCREMENT,
  `nameSubscription` VARCHAR(45) NOT NULL,
  `lastSubscription` VARCHAR(45) NOT NULL,
  `priceSubscription` FLOAT NOT NULL,
  PRIMARY KEY (`idSubscriptionCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Subscription` (
  `idSubscriptionType` INT NOT NULL AUTO_INCREMENT,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  `SubscriptionCategory_idSubscriptionCategory` INT NOT NULL,
  PRIMARY KEY (`idSubscriptionType`),
  CONSTRAINT `fk_Subscription_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscription_SubscriptionCategory1`
    FOREIGN KEY (`SubscriptionCategory_idSubscriptionCategory`)
    REFERENCES `db_fitness`.`SubscriptionCategory` (`idSubscriptionCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscription_Customer1_idx` ON `db_fitness`.`Subscription` (`Customer_Users_username` ASC);

CREATE INDEX `fk_Subscription_SubscriptionCategory1_idx` ON `db_fitness`.`Subscription` (`SubscriptionCategory_idSubscriptionCategory` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`ConnectedWatchCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`ConnectedWatchCategory` (
  `idConnectedWatchCategory` INT NOT NULL AUTO_INCREMENT,
  `modelWatch` VARCHAR(45) NOT NULL,
  `priceConnectedWatch` FLOAT NOT NULL,
  PRIMARY KEY (`idConnectedWatchCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`ConnectedWatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`ConnectedWatch` (
  `idConnectedWatch` INT NOT NULL AUTO_INCREMENT,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  `ConnectedWatchCategory_idConnectedWatchCategory` INT NOT NULL,
  PRIMARY KEY (`idConnectedWatch`),
  CONSTRAINT `fk_ConnectedWatch_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectedWatch_ConnectedWatchCategory1`
    FOREIGN KEY (`ConnectedWatchCategory_idConnectedWatchCategory`)
    REFERENCES `db_fitness`.`ConnectedWatchCategory` (`idConnectedWatchCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConnectedWatch_Customer1_idx` ON `db_fitness`.`ConnectedWatch` (`Customer_Users_username` ASC);

CREATE INDEX `fk_ConnectedWatch_ConnectedWatchCategory1_idx` ON `db_fitness`.`ConnectedWatch` (`ConnectedWatchCategory_idConnectedWatchCategory` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Room` (
  `idRoom` INT NOT NULL AUTO_INCREMENT,
  `capacityRoom` INT NOT NULL,
  `nameRoom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`FacilityCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`FacilityCategory` (
  `idFacilityCategory` INT NOT NULL AUTO_INCREMENT,
  `nameFacilityategory` VARCHAR(45) NOT NULL,
  `quantityFacilityCategory` INT NOT NULL,
  `priceFacilityCategory` FLOAT NOT NULL,
  PRIMARY KEY (`idFacilityCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Facility` (
  `idFacility` INT NOT NULL AUTO_INCREMENT,
  `nameFacility` VARCHAR(45) NOT NULL,
  `priceSeance` FLOAT NOT NULL DEFAULT 0,
  `Room_idRoom` INT NOT NULL,
  `descriptionFacility` VARCHAR(45) NOT NULL,
  `imageFacility` VARCHAR(45) NULL,
  `FacilityCategory_idFacilityCategory` INT NOT NULL,
  PRIMARY KEY (`idFacility`),
  CONSTRAINT `fk_Equipement_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `db_fitness`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facility_FacilityCategory1`
    FOREIGN KEY (`FacilityCategory_idFacilityCategory`)
    REFERENCES `db_fitness`.`FacilityCategory` (`idFacilityCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipement_Room1_idx` ON `db_fitness`.`Facility` (`Room_idRoom` ASC);

CREATE UNIQUE INDEX `nameMaterial_UNIQUE` ON `db_fitness`.`Facility` (`nameFacility` ASC);

CREATE INDEX `fk_Facility_FacilityCategory1_idx` ON `db_fitness`.`Facility` (`FacilityCategory_idFacilityCategory` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Seance` (
  `idSeance` INT NOT NULL AUTO_INCREMENT,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  `statusSeance` INT NULL DEFAULT 0,
  `dateOfSeance` DATETIME NULL,
  `nbTimestamp` INT NULL,
  PRIMARY KEY (`idSeance`),
  CONSTRAINT `fk_Seance_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seance_Customer1_idx` ON `db_fitness`.`Seance` (`Customer_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`SessionTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SessionTraining` (
  `idSessionTraining` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `capacityAttendant` INT NOT NULL,
  `Staff_Users_username` VARCHAR(45) NOT NULL,
  `Room_idRoom` INT NOT NULL,
  `priceSessionTraining` FLOAT NOT NULL,
  PRIMARY KEY (`idSessionTraining`),
  CONSTRAINT `fk_SessionTraining_Staff1`
    FOREIGN KEY (`Staff_Users_username`)
    REFERENCES `db_fitness`.`Staff` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `db_fitness`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SessionTraining_Staff1_idx` ON `db_fitness`.`SessionTraining` (`Staff_Users_username` ASC);

CREATE INDEX `fk_SessionTraining_Room1_idx` ON `db_fitness`.`SessionTraining` (`Room_idRoom` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `typeItem` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `Subscription_idSubscriptionType` INT NULL,
  `ConnectedWatch_idConnectedWatch` INT NULL,
  `Seance_idSeance` INT NULL,
  `SessionTraining_idSessionTraining` INT NULL,
  `PriceItemCategory_idPriceItemCategory` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  CONSTRAINT `fk_Prestation_Subscription1`
    FOREIGN KEY (`Subscription_idSubscriptionType`)
    REFERENCES `db_fitness`.`Subscription` (`idSubscriptionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestation_ConnectedWatch1`
    FOREIGN KEY (`ConnectedWatch_idConnectedWatch`)
    REFERENCES `db_fitness`.`ConnectedWatch` (`idConnectedWatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `db_fitness`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_SessionTraining1`
    FOREIGN KEY (`SessionTraining_idSessionTraining`)
    REFERENCES `db_fitness`.`SessionTraining` (`idSessionTraining`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prestation_Subscription1_idx` ON `db_fitness`.`Item` (`Subscription_idSubscriptionType` ASC);

CREATE INDEX `fk_Prestation_ConnectedWatch1_idx` ON `db_fitness`.`Item` (`ConnectedWatch_idConnectedWatch` ASC);

CREATE INDEX `fk_Purchase_Seance1_idx` ON `db_fitness`.`Item` (`Seance_idSeance` ASC);

CREATE INDEX `fk_Item_SessionTraining1_idx` ON `db_fitness`.`Item` (`SessionTraining_idSessionTraining` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Command` (
  `idCommand` INT NOT NULL AUTO_INCREMENT,
  `dateOfCommand` DATETIME NOT NULL,
  `totalPrice` FLOAT NOT NULL,
  `statusCommand` INT NOT NULL DEFAULT 0,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCommand`),
  CONSTRAINT `fk_Command_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Command_Customer1_idx` ON `db_fitness`.`Command` (`Customer_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`SessionTraining_has_Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SessionTraining_has_Customer` (
  `SessionTraining_idSessionTraining` INT NOT NULL,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SessionTraining_idSessionTraining`, `Customer_Users_username`),
  CONSTRAINT `fk_SessionTraining_has_Customer_SessionTraining1`
    FOREIGN KEY (`SessionTraining_idSessionTraining`)
    REFERENCES `db_fitness`.`SessionTraining` (`idSessionTraining`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_has_Customer_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SessionTraining_has_Customer_Customer1_idx` ON `db_fitness`.`SessionTraining_has_Customer` (`Customer_Users_username` ASC);

CREATE INDEX `fk_SessionTraining_has_Customer_SessionTraining1_idx` ON `db_fitness`.`SessionTraining_has_Customer` (`SessionTraining_idSessionTraining` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`TimestampFacility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`TimestampFacility` (
  `idTimestampFacility` INT NOT NULL AUTO_INCREMENT,
  `dateOfTimestamp` DATETIME NOT NULL,
  `Facility_idFacility` INT NOT NULL,
  `Seance_idSeance` INT NOT NULL,
  `FacilityCategory_idFacilityCategory` INT NOT NULL,
  PRIMARY KEY (`idTimestampFacility`),
  CONSTRAINT `fk_TimestampFacility_Facility1`
    FOREIGN KEY (`Facility_idFacility`)
    REFERENCES `db_fitness`.`Facility` (`idFacility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TimestampFacility_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `db_fitness`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TimestampFacility_FacilityCategory1`
    FOREIGN KEY (`FacilityCategory_idFacilityCategory`)
    REFERENCES `db_fitness`.`FacilityCategory` (`idFacilityCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TimestampFacility_Facility1_idx` ON `db_fitness`.`TimestampFacility` (`Facility_idFacility` ASC);

CREATE INDEX `fk_TimestampFacility_Seance1_idx` ON `db_fitness`.`TimestampFacility` (`Seance_idSeance` ASC);

CREATE INDEX `fk_TimestampFacility_FacilityCategory1_idx` ON `db_fitness`.`TimestampFacility` (`FacilityCategory_idFacilityCategory` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`MaintenanceOperation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`MaintenanceOperation` (
  `idMaintenanceOperation` INT NOT NULL AUTO_INCREMENT,
  `priceMaintenanceOperation` FLOAT NOT NULL,
  `dateOfIntervention` DATETIME NOT NULL,
  `Facility_idFacility` INT NOT NULL,
  PRIMARY KEY (`idMaintenanceOperation`),
  CONSTRAINT `fk_MaintenanceOperation_Facility1`
    FOREIGN KEY (`Facility_idFacility`)
    REFERENCES `db_fitness`.`Facility` (`idFacility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MaintenanceOperation_Facility1_idx` ON `db_fitness`.`MaintenanceOperation` (`Facility_idFacility` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Command_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Command_has_Item` (
  `Command_idCommand` INT NOT NULL,
  `Item_idItem` INT NOT NULL,
  PRIMARY KEY (`Command_idCommand`, `Item_idItem`),
  CONSTRAINT `fk_Command_has_Item_Command1`
    FOREIGN KEY (`Command_idCommand`)
    REFERENCES `db_fitness`.`Command` (`idCommand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Command_has_Item_Item1`
    FOREIGN KEY (`Item_idItem`)
    REFERENCES `db_fitness`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Command_has_Item_Item1_idx` ON `db_fitness`.`Command_has_Item` (`Item_idItem` ASC);

CREATE INDEX `fk_Command_has_Item_Command1_idx` ON `db_fitness`.`Command_has_Item` (`Command_idCommand` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
